FROM python:3.12.1-alpine

RUN apk update

WORKDIR /app

COPY ./serveur/ /app/

RUN pip install -r requirements.txt

CMD [ "flask", "--app", "srv", "run","--host", "0.0.0.0" ,"--port", "5000", "--debug"]
