FROM python:3.12.1-alpine

RUN apk update

WORKDIR /app

COPY ./api-controle/ /app/

RUN pip install -r requirements.txt

CMD [ "flask", "--app", "api-controle", "run","--host", "0.0.0.0", "--port", "5000","--debug"]