FROM python:3.12.1-alpine

RUN apk update

WORKDIR /app

COPY ./srv-controle/ /app/

RUN pip install -r requirements.txt

CMD [ "flask", "--app", "srv-controle", "run","--host", "0.0.0.0" ,"--port", "5000", "--debug"]
