FROM python:3.12.1-slim-bookworm
# FROM python:3.12.1-alpine

# RUN apk update

# RUN apt-get install libzbar0

RUN apt-get update

RUN apt install libzbar0 -y

WORKDIR /app

COPY ./scanner-qrcode/ /app/


RUN pip install -r requirements.txt


CMD [ "flask", "--app", "scanner-qrcode", "run", "--host", "0.0.0.0", "--port", "5000", "--debug"]






# docker pull python:3.12.1-slim-bookworm